-- 既存のUSERSテーブルを削除（制約なども一緒に削除されます）
DROP TABLE IF EXISTS "USERS" CASCADE;

-- 正しい型でUSERSテーブルを再作成
CREATE TABLE "USERS" (
  "id" UUID PRIMARY KEY,  -- int8からUUIDに変更
  "name" VARCHAR(50) NOT NULL,
  "email" VARCHAR(100) NOT NULL UNIQUE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE,
  "is_active" BOOLEAN DEFAULT TRUE NOT NULL
);

-- デフォルト値の設定を確認
ALTER TABLE "USERS" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "USERS" ALTER COLUMN "is_active" SET DEFAULT TRUE; 